import dayjs from 'dayjs'
import { Task } from './types'
import { isToday, isThisWeek, isNextWeek, isOverdue, startOfWeek, endOfWeek } from '../utils/dateUtils'

const DOMAINS = ['work', 'personal', 'personal-projects']

function getPriority(task: Task): string {
  if (task.tags.includes('priority/high')) return 'High'
  if (task.tags.includes('priority/low')) return 'Low'
  return 'Medium'
}

function getDomain(task: Task): string {
  for (const d of DOMAINS) {
    if (task.tags.includes(d)) return d.replace('-', ' ').replace(/\b\w/g, (c) => c.toUpperCase())
  }
  return 'Inbox'
}

function taskLine(task: Task): string {
  const domain = getDomain(task)
  const priority = getPriority(task)
  const due = task.due ? ` *(due ${dayjs(task.due).format('MMM D')})*` : ''
  return `- [ ] ${task.name}${due} — ${domain} · ${priority} <!-- task:${task.id} -->`
}

function isActive(task: Task): boolean {
  return !task.tags.includes('status/done') && !task.tags.includes('status/blocked')
}

export function generateTodayNote(tasks: Task[]): string {
  const active = tasks.filter(isActive)
  const overdue = active.filter((t) => t.due && isOverdue(t.due))
  const dueToday = active.filter((t) => t.due && isToday(t.due))
  const inbox = active.filter((t) => t.tags.includes('status/inbox'))

  const dateStr = dayjs().format('MMMM D, YYYY')
  const timestamp = dayjs().format('YYYY-MM-DD HH:mm')

  const sections: string[] = [`# Today — ${dateStr}`]

  if (inbox.length > 0) {
    sections.push('\n## Needs Triage')
    inbox.forEach((t) => sections.push(taskLine(t)))
  }

  sections.push('\n## Overdue')
  if (overdue.length > 0) {
    overdue.forEach((t) => sections.push(taskLine(t)))
  } else {
    sections.push('*(Nothing overdue)*')
  }

  sections.push('\n## Due Today')
  if (dueToday.length > 0) {
    dueToday.forEach((t) => sections.push(taskLine(t)))
  } else {
    sections.push('*(Nothing due today)*')
  }

  sections.push(`\n---\n*Generated by task-manager · /today · ${timestamp}*`)
  return sections.join('\n')
}

export function generateThisWeekNote(tasks: Task[]): string {
  const weekStart = startOfWeek()
  const weekEnd = endOfWeek()
  const active = tasks.filter(isActive).filter((t) => t.due && isThisWeek(t.due))
  const timestamp = dayjs().format('YYYY-MM-DD HH:mm')
  const rangeStr = `${dayjs(weekStart).format('MMM D')}–${dayjs(weekEnd).format('MMM D, YYYY')}`

  const sections: string[] = [`# This Week — ${rangeStr}`]

  for (const domain of DOMAINS) {
    const domainTasks = active.filter((t) => t.tags.includes(domain))
    const label = domain.replace('-', ' ').replace(/\b\w/g, (c) => c.toUpperCase())
    sections.push(`\n## ${label}`)
    if (domainTasks.length > 0) {
      domainTasks.forEach((t) => sections.push(taskLine(t)))
    } else {
      sections.push('*(Nothing scheduled yet)*')
    }
  }

  sections.push(`\n---\n*Generated by task-manager · /today · ${timestamp}*`)
  return sections.join('\n')
}

export function generateNextWeekNote(tasks: Task[]): string {
  const nextWeekDate = dayjs().add(7, 'day').format('YYYY-MM-DD')
  const nextStart = startOfWeek(nextWeekDate)
  const nextEnd = endOfWeek(nextWeekDate)
  const active = tasks.filter(isActive).filter((t) => t.due && isNextWeek(t.due))
  const timestamp = dayjs().format('YYYY-MM-DD HH:mm')
  const rangeStr = `${dayjs(nextStart).format('MMM D')}–${dayjs(nextEnd).format('MMM D, YYYY')}`

  const sections: string[] = [`# Next Week — ${rangeStr}`]

  for (const domain of DOMAINS) {
    const domainTasks = active.filter((t) => t.tags.includes(domain))
    const label = domain.replace('-', ' ').replace(/\b\w/g, (c) => c.toUpperCase())
    sections.push(`\n## ${label}`)
    if (domainTasks.length > 0) {
      domainTasks.forEach((t) => sections.push(taskLine(t)))
    } else {
      sections.push('*(Nothing scheduled yet)*')
    }
  }

  sections.push(`\n---\n*Generated by task-manager · /today · ${timestamp}*`)
  return sections.join('\n')
}

export function parseCheckedTaskIds(noteContent: string): string[] {
  const lines = noteContent.split('\n')
  const ids: string[] = []
  for (const line of lines) {
    if (/^- \[x\]/.test(line)) {
      const match = line.match(/<!-- task:(task-[\w-]+) -->/)
      if (match) ids.push(match[1])
    }
  }
  return ids
}
